# Junk edit for triggering the linter, we'll see how we go!
name: Super Cool Compose Stack
services:
  api:
    image: mysupercoolapp:latest-${NODE_ENV}
    build: 
      context: .
      args:
        - PORT=5555
    env_file: .env
    environment:
    # Interpolated variables can have a fallback value using ":-"
      - DATABASE_URL=mongodb://mongo:27017/mycoolappdatabase-${NODE_ENV:-defaultenvironment}
      - PORT=${PORT:-5000}
    ports:
      - 5432:${PORT:-5000}
      - 65535:${PORT:-5000}
      - 1025:${PORT:-5000}
  mongo:
    image: mongo
    ports:
      - 54321:27017
    volumes:
      # - ./mongodbdata:/data/db
      - mongodb-data:/data/db

# Using volumes like this stores the data in a Docker-managed location, typically a hidden folder.
# e.g. \\wsl$\docker-desktop-data\data\docker\volumes on Windows
# or    /var/lib/docker/volumes on Linux-based systems
volumes:
  mongodb-data:
    driver: local

    